global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'umms-api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.13.71:8080']
        labels:
          application: 'API Gateway'
  - job_name: 'umms-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.13.71:8081']
        labels:
          application: 'User Service'
  - job_name: 'umms-service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.13.71:8761']
        labels:
          application: 'Service Discovery'
  - job_name: 'umms-mortgage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.13.71:8082']
        labels:
          application: 'Mortgage Service'
  - job_name: 'umms-notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.13.71:8083']
        labels:
          application: 'Notification Service'